"""Plugin for Ansible
This plugin defines two main functions:
 .. 1. generate command based on input args;
 .. 2. execute command generated by 1);
To fulfill functionality above, 3rd plugin module must implement
functions below:
 .. 1. gen_executive(*args, **kwargs);
 .. 2. execute(*args, **kwargs);

Version 0.1: execute command on remote host directly
Version 0.2: encapsulating ansible API
"""



from paramiko import SSHClient, AutoAddPolicy

#Function: generate executive(s)
# .. param: args, type: dict
def gen_executive():
    """Definition"""


#Function: execute -- to execute command(s) generated above
def execute():
    """Definition"""



if __name__ == '__main__':
    ssh = SSHClient()
    ssh.set_missing_host_key_policy(AutoAddPolicy())
    ssh.connect(hostname='10.10.100.131', port=22, username='root', password='admin@123')
    stdin, stdout, stderr = ssh.exec_command('ls')
    out = stdout.read()
    print(out.decode())

