"""add create_date for service

Revision ID: 213ea3769d64
Revises: 310c2d57bec7
Create Date: 2018-01-31 16:47:20.022898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213ea3769d64'
down_revision = '310c2d57bec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.add_column('apm_service', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'apm_service', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_resource', ['apm_resource_id'], ['apm_resource_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_service', type_='foreignkey')
    op.drop_column('apm_service', 'create_date')
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    # ### end Alembic commands ###
