"""empty message

Revision ID: 69101df7d54d
Revises: fe5390e5609f
Create Date: 2018-02-06 13:49:21.398963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69101df7d54d'
down_revision = 'fe5390e5609f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apm_resource', sa.Column('create_date', sa.DateTime(), nullable=True))
    op.add_column('apm_resource', sa.Column('remark', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_service', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.add_column('apm_svc_instance', sa.Column('remark', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'apm_svc_instance', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    op.create_foreign_key(None, 'apm_svc_instance', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_resource', ['apm_resource_id'], ['apm_resource_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_instance', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_instance', type_='foreignkey')
    op.drop_column('apm_svc_instance', 'remark')
    op.drop_constraint(None, 'apm_service', type_='foreignkey')
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    op.drop_column('apm_resource', 'remark')
    op.drop_column('apm_resource', 'create_date')
    # ### end Alembic commands ###
