"""drop remark of apm_resource

Revision ID: 8b846b156d6f
Revises: eef5d71ddd28
Create Date: 2018-01-31 12:05:05.834771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8b846b156d6f'
down_revision = 'eef5d71ddd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.drop_column('apm_resource', 'remark')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apm_resource', sa.Column('remark', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    # ### end Alembic commands ###
