"""initial migration

Revision ID: c921dc1f3b2d
Revises: 
Create Date: 2018-01-31 11:39:26.599696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c921dc1f3b2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    # ### end Alembic commands ###
