"""add table apm_svc_instance

Revision ID: fe2436efc707
Revises: 213ea3769d64
Create Date: 2018-01-31 17:19:09.976013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe2436efc707'
down_revision = '213ea3769d64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apm_svc_instance',
    sa.Column('apm_svc_inst_id', sa.Integer(), nullable=False),
    sa.Column('apm_svc_inst_name', sa.String(length=128), nullable=True),
    sa.Column('apm_service_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('create_date', sa.DateTime(), nullable=True),
    sa.Column('apm_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['apm_service_id'], ['apm_service.apm_service_id'], ),
    sa.ForeignKeyConstraint(['apm_user_id'], ['apm_user.apm_user_id'], ),
    sa.PrimaryKeyConstraint('apm_svc_inst_id')
    )
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_service', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_resource', ['apm_resource_id'], ['apm_resource_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_service', type_='foreignkey')
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    op.drop_table('apm_svc_instance')
    # ### end Alembic commands ###
