"""add remark for service table 

Revision ID: fe5390e5609f
Revises: fe2436efc707
Create Date: 2018-01-31 22:32:04.413254

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe5390e5609f'
down_revision = 'fe2436efc707'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    op.create_foreign_key(None, 'apm_resource', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.add_column('apm_service', sa.Column('remark', sa.String(length=255), nullable=True))
    op.create_foreign_key(None, 'apm_service', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_svc_instance', 'apm_user', ['apm_user_id'], ['apm_user_id'])
    op.create_foreign_key(None, 'apm_svc_instance', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_service', ['apm_service_id'], ['apm_service_id'])
    op.create_foreign_key(None, 'apm_svc_res_rel', 'apm_resource', ['apm_resource_id'], ['apm_resource_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_res_rel', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_instance', type_='foreignkey')
    op.drop_constraint(None, 'apm_svc_instance', type_='foreignkey')
    op.drop_constraint(None, 'apm_service', type_='foreignkey')
    op.drop_column('apm_service', 'remark')
    op.drop_constraint(None, 'apm_resource', type_='foreignkey')
    op.create_table('test',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='MyISAM'
    )
    # ### end Alembic commands ###
